*java.security.cert.CertStoreException* *CertStoreException* An exception indica

public class CertStoreException
  extends    |java.security.GeneralSecurityException|

|java.security.cert.CertStoreException_Description|
|java.security.cert.CertStoreException_Fields|
|java.security.cert.CertStoreException_Constructors|
|java.security.cert.CertStoreException_Methods|

================================================================================

*java.security.cert.CertStoreException_Constructors*
|java.security.cert.CertStoreException()|Creates aCertStoreExceptionwithnullas 
|java.security.cert.CertStoreException(String)|Creates aCertStoreExceptionwith 
|java.security.cert.CertStoreException(String,Throwable)|Creates aCertStoreExce
|java.security.cert.CertStoreException(Throwable)|Creates aCertStoreExceptionth

*java.security.cert.CertStoreException_Description*

An exception indicating one of a variety of problems retrieving certificates 
and CRLs from aCertStore. 

ACertStoreExceptionprovides support for wrapping exceptions. The 
getCause(|java.security.cert.CertStoreException|) method returns the throwable, 
if any, that caused this exception to be thrown. 

Concurrent Access 

Unless otherwise specified, the methods defined in this class are not 
thread-safe. Multiple threads that need to access a single object concurrently 
should synchronize amongst themselves and provide the necessary locking. 
Multiple threads each manipulating separate objects need not synchronize. 



*java.security.cert.CertStoreException()*

public CertStoreException()

Creates aCertStoreExceptionwithnullas its detail message. 


*java.security.cert.CertStoreException(String)*

public CertStoreException(java.lang.String msg)

Creates aCertStoreExceptionwith the given detail message. A detail message is 
aStringthat describes this particular exception. 

    msg - the detail message 

*java.security.cert.CertStoreException(String,Throwable)*

public CertStoreException(
  java.lang.String msg,
  java.lang.Throwable cause)

Creates aCertStoreExceptionwith the specified detail message and cause. 

    msg - the detail message 
    cause - the cause (which is saved for later retrieval by the {@link #getCause 
       getCause()} method). (A {@code null} value is permitted, and indicates 
       that the cause is nonexistent or unknown.) 

*java.security.cert.CertStoreException(Throwable)*

public CertStoreException(java.lang.Throwable cause)

Creates aCertStoreExceptionthat wraps the specified throwable. This allows any 
exception to be converted into aCertStoreException, while retaining information 
about the cause, which may be useful for debugging. The detail message is set 
to (cause==null ? null : cause.toString()) (which typically contains the class 
and detail message of cause). 

    cause - the cause (which is saved for later retrieval by the {@link #getCause 
       getCause()} method). (A {@code null} value is permitted, and indicates 
       that the cause is nonexistent or unknown.) 

